resolver: ghc-8.6.5

packages:
  - ghc-asterius
  - ghc-bin-asterius
  - ghc-boot-asterius
  - ghc-boot-th-asterius
  - ghc-heap-asterius
  - ghc-pkg-asterius
  - ghci-asterius
  - template-haskell-asterius

extra-deps:
  - Cabal-3.0.1.0

ghc-options:
  $everything: -j
