name: pipeline

on:
  - push
  - pull_request

jobs:

  vanilla:
    name: vanilla
    runs-on: ubuntu-20.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@main
        with:
          ghc-version: 8.8.4
          stack-version: 2.5.1
          enable-stack: true

      - name: checkout
        uses: actions/checkout@v2

      - name: materialize
        run: |
          mkdir ~/.stack
          echo "system-ghc: true" > ~/.stack/config.yaml

          ./make-packages.py

      - name: test
        run: |
          stack build --fast

  profile:
    name: profile
    runs-on: ubuntu-20.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@main
        with:
          ghc-version: 8.8.4
          stack-version: 2.5.1
          enable-stack: true

      - name: setup-haskell-extra
        run: |
          sudo apt install -y ghc-8.8.4-prof

      - name: checkout
        uses: actions/checkout@v2

      - name: materialize
        run: |
          mkdir ~/.stack
          echo "system-ghc: true" > ~/.stack/config.yaml

          ./make-packages.py

      - name: test
        run: |
          stack build --fast --profile
